name: CD - Deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  deploy:
    # Run on direct pushes to main OR when PR is merged to main
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    name: Deploy Application
    runs-on: ubuntu-latest
    
    # OIDC認証のためのアクセス許可を設定
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
      
      # AWSとのOIDC連携を設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      
      # フロントエンドのビルド
      - name: Install frontend dependencies
        working-directory: ./app
        run: npm ci
      
      - name: Build frontend
        working-directory: ./app
        run: npm run build
      
      # CDK準備とデプロイ
      - name: Install CDK dependencies
        working-directory: ./infra
        run: npm ci
      
      # CDKデプロイ - OIDC認証を使用
      - name: Deploy with CDK
        working-directory: ./infra
        run: npx cdk deploy --all --require-approval never
        env:
          # DBの接続情報をCDKに渡す
          DB_HOST: ${{ secrets.PROD_DB_HOST }}
          DB_PORT: ${{ secrets.PROD_DB_PORT }}
          DB_NAME: ${{ secrets.PROD_DB_NAME }}
          DB_USER: ${{ secrets.PROD_DB_USER }}
          DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      
      # S3へのフロントエンドのデプロイ
      - name: Deploy frontend to S3
        run: |
          # CDK出力からS3バケット名を取得
          S3_BUCKET=$(aws cloudformation describe-stacks --stack-name TechLibStack --query "Stacks[0].Outputs[?OutputKey=='WebsiteBucketName'].OutputValue" --output text)
          
          # S3バケットにビルドファイルをアップロード
          aws s3 sync ./app/dist/ s3://$S3_BUCKET/ --delete
      
      - name: Output deployment information
        working-directory: ./infra
        run: npx cdk output --json > ../deployment-output.json
          