name: CI - Test

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    # PostgreSQLサービスコンテナを追加
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: tech_lib
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tech_lib_test
        ports:
          - 5432:5432
        # ヘルスチェックを追加してPostgreSQLが起動完了するのを待つ
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
      
      # データベースのセットアップ: 外部SQLファイルを使用
      - name: Setup database using SQL files
        run: |
          # DDLの実行（テーブル構造の作成）
          PGPASSWORD=postgres psql -h localhost -U tech_lib -d tech_lib_test -f database/ddl.sql
          
          # DMLの実行（初期データの挿入）
          PGPASSWORD=postgres psql -h localhost -U tech_lib -d tech_lib_test -f database/dml.sql
          
          echo "Database setup completed successfully"
      
      # フロントエンド（Vue.js）のテスト
      - name: Install frontend dependencies
        working-directory: ./app
        run: npm ci
      
      - name: Run frontend tests
        working-directory: ./app
        run: npm test
      
      - name: Lint frontend code
        working-directory: ./app
        run: npm run lint
      